[build-system]
requires = ["setuptools>=66.1"]
build-backend = "setuptools.build_meta"

[project]
name = "choir-separator-project"
version = "0.1.0"
requires-python = ">=3.10, <3.13"
dependencies = [
	"huggingface-hub",
	"ipykernel>=7.3.0",
	"melband-roformer-infer",
	"PyYAML",
	"torch",
	"torchaudio",
	"ipykernel"
]

[tool.setuptools]
py-modules = []

[tool.uv]
package = false
index-url = "https://pypi.org/simple"
extra-index-url = []
index-strategy = "first-index"
